# Default values for tce-all-in-one.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 5
# mode can be (boot | peer)
mode: boot

# deploy a single TCE node per K8s node
singleTCENodePerK8sNode: true

host: nowhere.com
# create ingress (true | false)
ingress: false

acme:
  email: nobody@nowhere.com
  # acme issuer type (staging | production)
  environment: staging

ports:
  http: 1340
  p2p: 9090

image:
  repository: nobody
  tag: main

credentials:
  username: nobody
  password: secret

env:
  RUST_LOG: info,topos=info
  TCE_DB_PATH: /tmp/default-db
  TCE_API_ADDR: 0.0.0.0:1340
  TOPOS_OTLP_AGENT: tce-node
  TOPOS_OTLP_SERVICE_NAME: https://telemetry.nowhere.com
  TCE_ECHO_SAMPLE_SIZE: "6"
  TCE_READY_SAMPLE_SIZE: "6"
  TCE_DELIVERY_SAMPLE_SIZE: "6"
  TCE_ECHO_THRESHOLD: "2"
  TCE_READY_THRESHOLD: "2"
  TCE_DELIVERY_THRESHOLD: "2"
  LOCAL_TEST_NET: "true"
  TCE_LOCAL_KS: "1"
  RUST_BACKTRACE: full
  TOOLCHAIN_VERSION: stable
  TOPOS_OTLP_TAGS: key1=value1,key2=value2
  OTLP_BATCH_SCHEDULED_DELAY: 100
  OTLP_BATCH_MAX_CONCURRENT_EXPORTS: 1000
  OTLP_BATCH_MAX_EXPORTER_BATCH_SIZE: 10000
  OTLP_BATCH_EXPORT_TIMEOUT: 100000
  OTLP_BATCH_MAX_QUEUE_SIZE: 10000
